# docs: http://www.appveyor.com/docs/appveyor-yml
# software installed on build machines: http://www.appveyor.com/docs/installed-software

version: 3.1.{build}

branches:
  only:
    - master

# set env var when running in appveyor so that we can distinguish
# from running locally
environment:
  inappveyor: 1

skip_tags: true

build_script:
  - scripts\appveyor-build.bat

artifacts:
  - path: obj-rel\SumatraPDF.exe
  - path: obj-rel\SumatraPDF.pdb
  - path: obj-rel\SumatraPDF-no-MuPDF.exe
  - path: obj-rel\SumatraPDF-no-MuPDF.pdb
  - path: obj-rel\uninstall.exe
  - path: obj-rel\uninstall.pdb
  - path: obj-rel\libmupdf.dll
  - path: obj-rel\libmupdf.pdb
