name: emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  emscripten:
    env:
      EMSCRIPTEN_VERSION: 1.37.26
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install emscripten
      run: |
        ./scripts/install-ci-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Run tests
      run: |
        ./scripts/run-ci.sh
