name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpplint:
    env:
      CPPLINT: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        ./scripts/install-ci-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Check format
      run: |
        ./scripts/run-ci.sh

  licenses:
    env:
      CHECK_LICENSES: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        ./scripts/install-ci-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/prepare-ci.sh

    - name: Check licenses
      run: |
        ./scripts/run-ci.sh
