name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build-pre-rel, build-ramicro-pre-rel]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        env:
          CERT_PWD: ${{ secrets.CERT_PWD }}
        run: .\doit.bat -ci

      # a separate step from -ci to make logs easier to read
      - name: Upload to s3 etc.
        env:
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
          SPACES_KEY: ${{ secrets.SPACES_KEY }}
          SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
        run: .\doit.bat -ci-upload
