name: Daily build
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [build-daily]
jobs:
  build:
    name: Build
    runs-on: SumatraBuilder
    #runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        env:
          CERT_PWD: ${{ secrets.CERT_PWD }}
          R2_SECRET: ${{ secrets.R2_SECRET }}
          R2_ACCESS: ${{ secrets.R2_ACCESS }}
          BB_SECRET: ${{ secrets.BB_SECRET }}
          BB_ACCESS: ${{ secrets.BB_ACCESS }}
        run: .\doit.bat -ci-daily

      # a separate step from -ci to make logs easier to read
      - name: Upload to spaces and s3
        env:
          R2_SECRET: ${{ secrets.R2_SECRET }}
          R2_ACCESS: ${{ secrets.R2_ACCESS }}
          BB_SECRET: ${{ secrets.BB_SECRET }}
          BB_ACCESS: ${{ secrets.BB_ACCESS }}
        run: .\doit.bat -ci-upload
